openapi: '3.0.3'
info:
  title: Schedule Rest Api
  description: API Spec for Doctor Restfull API
  version: '1.0'
servers:
  - url: http://127.0.0.1:8002/rest/v1
paths:
  /schedule:
    post:
      summary: Menambah data Schedule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                date:
                  type: string
                  format: date
                start_time:
                  type: string
                  pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
                end_time:
                  type: string
                  pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$"                
      responses:
        '201':
          description: "Created"

    get:
      summary: menampilkan data Schedule
      description: menampilkan tanpa menggunkan paginate
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    doctor_id:
                      type: integer
                    date:
                      type: string
                      format: date
                    start_time:
                      type: string
                      pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
                    end_time:
                      type: string
                      pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$" 
  /doctor?id=eq.id:  
    patch:
      summary: merubah data berdasarkan field dan id
      parameters:
        - name: id
          in: path
          required: true
          description: data Schedule id yang akan diambil
          schema:
            type: number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                date:
                  type: string
                  format: date
                start_time:
                  type: string
                  pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$"
                end_time:
                  type: string
                  pattern: "^[0-9]{2}:[0-9]{2}:[0-9]{2}$" 
      responses:
        '204':
          description: No Content  
    delete:
      summary: menghapus data Schedule
      parameters:
        - name: id
          in: path
          required: true
          description: data Schedule id yang akan diambil
          schema:
            type: number
      responses:
        '204':
          description: "No Content"           