PROJECT_NAME: medpoints-system
PROJECT_ID: illmqbrdabvqrgslbmqu
DEPLOYMENT_TARGET: cloud

MODE: bff
ACCESS_TOKEN: sbp_d23d11b9025107ba6fbe9efb172dc69fb523ee92
ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbnVvYWR4ZHV5dmhtbW9vbGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyOTEyOTAsImV4cCI6MjA1NTg2NzI5MH0.I9HOb8l6s_nbuSDeeSbznu6kmptCDeahM3lFhcboqe0
SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbnVvYWR4ZHV5dmhtbW9vbGp6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDI5MTI5MCwiZXhwIjoyMDU1ODY3MjkwfQ.ype0TporSlxbo6xg3dBxzXzXzV1tXFEnu78UXHsRUfo

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_API_TOKEN: 
SUPABASE_API_TOKEN_TYPE: 
SUPABASE_PUBLIC_URL: https://illmqbrdabvqrgslbmqu.supabase.co
SERVER_HOST: 127.0.0.1
SERVER_PORT: 8002
SERVER_DNS: 

ENVIRONMENT: development
VERSION: 1.0.0

ALLOWED_TABLES: '*'
SCHEDULE_STATUS: 'off'

BREAKER_ENABLE: false

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

MAX_SERVER_REQUEST_BODY_SIZE: 8388608

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
